quincy_source:
  gdrive_id: "1RHJXqEIPGSvEZWUy2wkIFul3eGXhPNeq"
  local_dir: "quincy"

data:
  gdrive_url: "https://drive.google.com/drive/folders/1WCaI9e6jUUmfpc-Q2aSdms15qEqOopFQ"
  local_dir: "data"